version: '3'
services:
  strapi:
    build:
      context: ./Strapi
    container_name: strapi
    env_file:
     - ./Strapi/.env
    ports:
      - "1337:1337"
    networks:
      - custom_net
      
  landing:
    build:
      context: ./Landing
      dockerfile: Dockerfile
    container_name: landing
    ports:
      - "3000:3000"
    networks:
      - custom_net
    depends_on:
      - strapi

networks:
  custom_net:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 192.168.1.0/24
          gateway: 192.168.1.1