version: '3'

services:
  db:
    image: postgres:13.0
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=test
    command: ["postgres", "-c", "listen_addresses=0.0.0.0"]
    volumes:
      - .\dump.sql:/docker-entrypoint-initdb.d/10-dump.sql
    restart: always  # This ensures the container restarts and re-runs the init scripts on restart

  strapi:
    build:
      context: ./Strapi
    container_name: strapi
    env_file:
     - ./Strapi/.env
    ports:
      - "3001:3001"
    depends_on:
      - db

  landing:
    build:
      context: ./Landing
      dockerfile: Dockerfile
    container_name: landing
    ports:
      - "3000:3000"
    depends_on:
      - strapi
