version: '3'
services:
  strapi:
    build:
      context: ./Strapi
    container_name: strapi
    env_file:
     - ./Strapi/.env
    ports:
      - "1337:1337"
      
  landing:
    build:
      context: ./Landing
      dockerfile: Dockerfile
    container_name: landing
    ports:
      - "3000:3000"
    depends_on:
      - strapi
